name: starter

services:
  postgres:
    image: docker.io/postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./store/postgres:/postgres"
      - "./store/data:/data"
      - ".:/project"
    environment:
      PGDATA: /db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    build:
      context: ./
      dockerfile: "./docker/django/Dockerfile"
    command: [ "/project/docker/django/run-dev.sh" ]
    environment:
      DJANGO_CONFIGURATION: Dev
      DJANGO_STORE_PATH: /store
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:8000"
    volumes:
      - "./:/project"
      - "./store/django:/store"
    depends_on:
      - postgres
